# Generated by Django 6.0.3 on 2026-03-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SongCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('HIPHOP', 'Hip-hop'), ('COUNTRY', 'Country')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm')], max_length=20)),
                ('occasion', models.CharField(max_length=200)),
                ('prompt_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file_path', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.library')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.songcreator')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.songcreator'),
        ),
        migrations.CreateModel(
            name='SongGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='songcreator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.user'),
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.user')),
            ],
        ),
    ]
